[package]
name = "life"
version = "0.1.0"
authors = ["John <salamonj9@gmail.com>"]

[dependencies]
gl = "*"
glium = "*"
glium_text_rusttype = { git = "https://github.com/human9/gtr-fork" }
cgmath = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

